<a href="https://colab.research.google.com/github/SupriyaAnne/DocTalk-A-Comprehensive-Healthcare-Solutions-Platform/blob/main/BMLLABEXT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**numpy**

In [ ]:
import numpy as np
list=[1,2,3,4]
vector=np.array(list)
print(vector)

[1 2 3 4]


In [ ]:
res=np.array(list)*2
print(res)

[2 4 6 8]


In [ ]:
res1=np.array(list)**2
print(res1)

[ 1  4  9 16]


In [ ]:
list1=[
    [1],
    [2],
    [3],
    [4]
]
vector2=np.array(list1)
print(vector2)

[[1]
 [2]
 [3]
 [4]]


In [ ]:
l1=[2,3,4,5]
l2=[6,7,8,9]
v1=np.array(l1)
v2=np.array(l2)
add=v1+v2
print("addition of vectors is",add)

addition of vectors is [ 8 10 12 14]


In [ ]:
l1=[2,3,4,5]
l2=[6,7,8,9]
v1=np.array(l1)
v2=np.array(l2)
mul=v1*v2
print(mul)

[12 21 32 45]


In [ ]:
print(v1.ndim)

1


**matrices**

In [ ]:
m1=[[1,2,3],[4,5,6],[7,8,9]]
m2=[[11,12,13],[14,15,16],[17,18,19]]
res=m1+m2
print(res)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13], [14, 15, 16], [17, 18, 19]]


In [ ]:
res=np.array(m2)-np.array(m1)
print(res)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
res1=np.array(m2)+np.array(m1)
print(res1)

[[12 14 16]
 [18 20 22]
 [24 26 28]]


In [ ]:
res2=np.array(m1)*np.array(m2)
print(res2)

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


**Array**

In [ ]:
import numpy as np
a1=[1,2,3]
a2=[4,5,6]
v1=np.array(a1)
v2=np.array(a2)
add=v1+v2
print(add)

[5 7 9]


In [ ]:
shape=v1.shape
print(shape)

(3,)


In [ ]:
reshape=v1.reshape(3,1)
print(reshape)

[[1]
 [2]
 [3]]


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
slice=arr[3:7]
print(slice)

[4 5 6 7]


In [ ]:
ar=np.array([1,2,3,4,5,6,7,8])
sum=np.sum(ar)
max=np.max(ar)
min=np.min(ar)
mean=np.mean(ar)
print(sum)
print(max)
print(min)
print(mean)

36
8
1
4.5


**LOADING DATA**
MANUAL


In [ ]:
import numpy as np
import pandas as pd
import pickle

In [ ]:
def load_csv(filepath):
  data=[]
  col=[]
  checkcol=False
  with open(filepath) as f:
    for val in f.readlines():
      val=val.replace("\n"," ")
      val=val.split(',')
      if checkcol is False:
        col=val
        checkcol=True
      else:
        data.append(val)
  df=pd.DataFrame(data=data,columns=col)
  return df

In [ ]:
myData = load_csv('/content/heyy hii hello.txt')
print(myData.head())

Empty DataFrame
Columns: [heyy hii hello]
Index: []


**loadtxt**

In [ ]:
df=np.loadtxt("/content/sample_data/mnist_test.csv",delimiter=',')
print(df[:5,:])

[[7. 0. 0. ... 0. 0. 0.]
 [2. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]]


**genfromtxt**

In [ ]:
content=np.genfromtxt("/content/heyy hii hello.txt",dtype=str,delimiter=",")
print("file data:",content)

file data: heyy hii hello


**read** **csv**

In [ ]:
data=pd.read_csv("/content/placement_cgpa.csv")
print(data.head())

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57


**pickle**

In [ ]:
l=[1,2,3,4]
with open('/content/heyy hii hello.txt','wb') as f:
  pickle.dump(l,f)
with open('/content/heyy hii hello.txt','rb') as f:
  d4=pickle.load(f)
print(d4)

[1, 2, 3, 4]


**Data** **Wrangling**

In [ ]:
import pandas as pd
data={'name':['rish','soup','shru','sush'],
      'age':[17,20,21,22],
      'gender':['F','F','M','M'],
      'marks':[202,15,'NaN',37]}
df=pd.DataFrame(data)
df

name  age gender marks
0  rish   17      F   202
1  soup   20      F    15
2  shru   21      M   NaN
3  sush   22      M    37

In [ ]:
c=avg=0
for ele in df['marks']:
  if str(ele).isnumeric():
    c+=1
    avg+=ele
avg/=c
df=df.replace(to_replace='NaN',value=avg)
df


name  age gender       marks
0  rish   17      F  202.000000
1  soup   20      F   15.000000
2  shru   21      M   84.666667
3  sush   22      M   37.000000

In [ ]:
df['gender']=df['gender'].map({'M':0,'F':1}).astype(float)
df

name  age  gender       marks
0  rish   17     NaN  202.000000
1  soup   20     NaN   15.000000
2  shru   21     NaN   84.666667
3  sush   22     NaN   37.000000

In [ ]:
import pandas as pd
details = pd.DataFrame({
	'ID': [101, 102, 103, 104, 105,
		106, 107, 108, 109, 110],
	'NAME': ['Jagroop', 'Praveen', 'Harjot',
			'Pooja', 'Rahul', 'Nikita',
			'Saurabh', 'Ayush', 'Dolly', "Mohit"],
	'BRANCH': ['CSE', 'CSE', 'CSE', 'CSE', 'CSE',
			'CSE', 'CSE', 'CSE', 'CSE', 'CSE']})
fees_status = pd.DataFrame(
	{'ID': [101, 102, 103, 104, 105,
			106, 107, 108, 109, 110],
	'PENDING': ['5000', '250', 'NIL',
				'9000', '15000', 'NIL',
				'4500', '1800', '250', 'NIL']})
print(pd.merge(details, fees_status, on='ID'))


    ID     NAME BRANCH PENDING
0  101  Jagroop    CSE    5000
1  102  Praveen    CSE     250
2  103   Harjot    CSE     NIL
3  104    Pooja    CSE    9000
4  105    Rahul    CSE   15000
5  106   Nikita    CSE     NIL
6  107  Saurabh    CSE    4500
7  108    Ayush    CSE    1800
8  109    Dolly    CSE     250
9  110    Mohit    CSE     NIL


In [ ]:
import pandas as pd
car_selling_data = {'Brand': ['Maruti', 'Maruti', 'Maruti',
							'Maruti', 'Hyundai', 'Hyundai',
							'Toyota', 'Mahindra', 'Mahindra',
							'Ford', 'Toyota', 'Ford'],
					'Year': [2010, 2011, 2009, 2013,
							2010, 2011, 2011, 2010,
							2013, 2010, 2010, 2011],
					'Sold': [6, 7, 9, 8, 3, 5,
							2, 8, 7, 2, 4, 2]}
df = pd.DataFrame(car_selling_data)
grouped = df.groupby('Year')
print(grouped(2010))


TypeError: ignored